spring:
  application:
    name: grpc-auth
    port: 9090
  authentication:
    project_id: ${PROJECT_ID:grpc-identity-platform-test}
  grpc:
    server:
      reflection:
        enabled: true # should be set to false in production